version: 0
metadata:
  name: "taskcluster-migration"
  description: "Automation for taskcluster/migration"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: "node:5.12"
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd migration && git checkout $GITHUB_HEAD_BRANCH && npm install && npm run build"
    metadata:
      name: "migrate graph update"
      description: "Update the migration work graph site"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    routes:
      - index.project.taskcluster.migration.latest
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    scopes:
        - "auth:aws-s3:read-write:migration-taskcluster-net/"
    payload:
      maxRunTime: 3600
      image: "node:5.12"
      features:
        taskclusterProxy: true
      env:
          PUBLISH_BUCKET: migration-taskcluster-net
          PUBLISH_REGION: us-east-1
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd migration && git checkout $GITHUB_HEAD_BRANCH && npm install && npm run build"
    metadata:
      name: "migrate graph update"
      description: "Update the migration work graph site"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
